package unipatches.overlay.presets

internal val luckyPatcherPreset = OverlayPresetDefinition(
    "luckyPatcher",
    "LuckyPatcher-inspired",
    "Original black-and-yellow UI inspired by Lucky Patcher.",
    explicitOverlayPreset(
        buttonText = "LP",
        background = "#000000",
        backgroundTransparency = 100,
        outline = "#FFFF00",
        overlayTextColor = "#FFFFFF",
        outlineWidth = 2,
        appendDescription = "Inspired by Lucky Patcher",
        appendDescriptionColor = "#FFFF00",
        buttonTextColor = "#FFFFFF",
        gradientBackground = true,
        buttonBackground = "#F0E60A",
        iconBackground2 = "#C6B407",
        iconGradientAngle = 0,
        iconOutline = true,
        iconOutlineColor = "#000000",
        iconOutlineWidth = 2,
        iconStyle = "parts",
        iconParts = listOf(
            "oval|35|38|12|16|0|solid|#000000|#000000|0|100|0",
            "oval|65|38|12|16|0|solid|#000000|#000000|0|100|0",
            "arc|50|56|48|32|0|solid|#000000|#000000|2|100|1",
            "oval|28|46|8|8|0|solid|#000000|#000000|0|100|2",
            "oval|72|46|8|8|0|solid|#000000|#000000|0|100|2",
        ),
        iconHighlight = true,
        controlTheme = "modern",
        controlBackground = "#FFFF00",
        controlForeground = "#B0FFFF",
        bottomButtonStyle = "gradient",
        bottomButtonShape = "squircle",
        bottomButtonPadding = true,
        bottomButtonTextColor = "#FFFF00",
        bottomButtonBackground1 = "#3A5A80",
        bottomButtonBackground2 = "#6E91B9",
        menuTextColor1 = "#FFFFFF",
        menuTextColor2 = "#00FF00",
        menuTextColor3 = "#B8B8B8",
        menuTextColor4 = "#D14DCA",
        menuTextColor5 = "#00FF00",
        menuTextColor6 = "#000000",
        menuTextColor7 = "#FFFF00",
        separatorBackgroundColor = "#D0D0D0",
        separatorStyle = "background",
        titleIconPlacement = "left",
        titleAlignment = "left",
        titleSeparator = true,
        menuCorners = "square",
        menuOutlineAnimation = "static",
        openingAnimation = "appearRight",
        closingAnimation = "disappearUp",
        animationDuration = 300,
        animationEasing = "linear",
    ),
)
