package unipatches.overlay.presets

internal val reVancedPreset = OverlayPresetDefinition(
    "reVanced",
    "ReVanced-inspired",
    "Original dark Material You-style UI inspired by ReVanced.",
    explicitOverlayPreset(
        buttonText = "RV",
        background = "#1B1B1D",
        backgroundTransparency = 90,
        outline = "#D5B8FF",
        overlayTextColor = "#B8D2FF",
        buttonTextColor = "#FFFFFF",
        outlineWidth = 4,
        appendDescription = "Inspired by ReVanced",
        appendDescriptionColor = "#D5B8FF",
        gradientBackground = false,
        buttonBackground = "#1B1B1B",
        iconBackground2 = "#1B1B1B",
        iconGradientAngle = 0,
        iconOutlineColor = "#EF4E99",
        iconOutlineGradient = true,
        iconOutlineColor2 = "#4E97F0",
        iconOutlineGradientAngle = 90,
        iconOutlineWidth = 3,
        iconOutline = true,
        iconStyle = "parts",
        iconParts = listOf(
            "chevron|50|52|64|72|0|solid|#FFFFFF|#FFFFFF|6|100|0",
            "triangle|50|39|28|22|0|gradient|#E651A0|#6564D3|0|100|1",
        ),
        iconHighlight = false,
        controlTheme = "monet",
        controlBackground = "#D5B8FF",
        controlForeground = "#C5D9FF",
        bottomButtonStyle = "solid",
        bottomButtonShape = "squircle",
        bottomButtonPadding = true,
        bottomButtonTextColor = "#D5B8FF",
        bottomButtonBackground1 = "#39304D",
        bottomButtonBackground2 = "#39304D",
        menuTextColor1 = "#B8D2FF",
        menuTextColor2 = "#D5B8FF",
        menuTextColor3 = "#D0D0D5",
        menuTextColor4 = "#8DB8F5",
        menuTextColor5 = "#8DB8F5",
        menuTextColor6 = "#A990D0",
        menuTextColor7 = "#D5B8FF",
        separatorStyle = "inline",
        menuOutlineAnimation = "gradient",
        openingAnimation = "scale",
        closingAnimation = "scale",
        animationDuration = 500,
        animationEasing = "logarithmic",
    ),
)
